### ISSUE TITLE
Use dictionary API to get definition for the keyword in "Metadata" section

### ISSUE THREAD

**Issue by ssyooo** [Architizer/mendel#33]
In the "Subject" section of our panel, we display the keyword to be tagged, as well as relevant information for context in order to make correct category assignments. We have one section to display the context in which the keyword came in the input data, as well as a section that displays the definition of the keyword. We want the definition section to query an API that will pull the dictionary definition of the keyword and display it alongside the context of the keyword.

**Comment by fredfalcon** [comment]
@sophiarch @expandrew I signed us for for Wordnik
