### ISSUE TITLE
Develop model

### ISSUE THREAD

**Issue by fredfalcon** [Architizer/mendel#6]
- [ ] **keyword** (has many categories, has many contexts)
- [ ] **category** (has many keywords)
- [ ] **context** (has one keyword)
- [ ] **review**
- [ ] created
- [ ] modified 
- [ ] user

**Comment by fredfalcon** [comment]
![pasted image at 2016_04_29 03_10 pm](https://cloud.githubusercontent.com/assets/7475382/14927013/60429654-0e1d-11e6-8c98-455cb490f1bd.png)

**Comment by fredfalcon** [comment]
User is done, comes build in with Django

**Comment by ssyooo** [comment]
![keyword and context input to output](https://cloud.githubusercontent.com/assets/18744347/14969365/f41d0f3e-108f-11e6-86a9-e1ac262ed0f4.jpg)

**Comment by sophiarch** [comment]
![pasted image at 2016_04_29 05_52 pm](https://cloud.githubusercontent.com/assets/18744347/14969371/fd981a4a-108f-11e6-9b8d-756f3aa37ff4.png)

**Comment by fredfalcon** [comment]
I believe Andrew is handling this.  Let me know.

**Comment by ssyooo** [comment]
<img width="805" alt="screen shot 2016-05-06 at 10 05 41 am" src="https://cloud.githubusercontent.com/assets/18744347/15123016/ae3d0770-15ef-11e6-8670-f275649de6c1.png">
