### ISSUE TITLE
"Exited with exit code 127" after running heroku local

### ISSUE THREAD

**Issue by chackerian** [Architizer/mendel#80]
Getting the following error when I run **heroku local**:

> 6:57:20 PM web.1 |      writing manifest file 'pip-egg-info/psycopg2.egg-info/SOURCES.txt'
> 6:57:20 PM web.1 |      warning: manifest_maker: standard file '-c' not found
> 6:57:20 PM web.1 |      Error: pg_config executable not found.
> 6:57:20 PM web.1 |      Please add the directory containing pg_config to the PATH
> 6:57:20 PM web.1 |      or specify the full executable path with the option:
> 6:57:20 PM web.1 |          python setup.py build_ext --pg-config /path/to/pg_config build ...
> 6:57:20 PM web.1 |      or with the pg_config option in 'setup.cfg'.
> 6:57:20 PM web.1 |      ----------------------------------------
> 6:57:21 PM web.1 |  Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/sz/nj_1cyfx43v3w6tjjsycf7r80000gn/T/pip-build-YEIecB/psycopg2/
> 6:57:21 PM web.1 |  python: can't open file 'manage.py': [Errno 2] No such file or directory
> 6:57:21 PM web.1 |  /bin/sh: gunicorn: command not found
> [DONE] Killing all processes with signal  null
> 6:57:21 PM web.1 Exited with exit code 127

I installed everything required but did get an error when running the setup script:

> writing dependency_links to pip-egg-info/psycopg2.egg-info/dependency_links.txt
>     writing manifest file 'pip-egg-info/psycopg2.egg-info/SOURCES.txt'
>     warning: manifest_maker: standard file '-c' not found
> 
> ```
> Error: pg_config executable not found.
> 
> Please add the directory containing pg_config to the PATH
> or specify the full executable path with the option:
> 
>     python setup.py build_ext --pg-config /path/to/pg_config build ...
> 
> or with the pg_config option in 'setup.cfg'.
> ----------------------------------------
> ```
> 
> Command "python setup.py egg_info" failed with error code 1 in /private/tmp/pip-build-WkoCRc/psycopg2/
> ./bin/setup_local: line 11: createdb: command not found

**Comment by fredfalcon** [comment]
From a quick look I would say to try 'pip install gunicorn' and make sure Postgres is installed and the pg_config tool is available on the path.

**Comment by chackerian** [comment]
I did both those things and got the server running but now getting "TemplateDoesNotExist at /api/"  when I go to http://0.0.0.0:5000/api/ in browser

**Comment by andrewwestling** [comment]
@chackerian

For the issue with the setup script, it looks like the Postgres command line tools might not be available on your `$PATH`

If you're using [Postgres.app](http://postgresapp.com), make sure the command line tools are set up. Check the directions in the link here: http://postgresapp.com/documentation/cli-tools.html

Sounds like you have the server running now, though - what happens when you go to http://localhost:5000/ ?

**Comment by chackerian** [comment]
I get "TemplateDoesNotExist at /"

**Comment by chackerian** [comment]
I can paste the console message too if that is helpful.

**Comment by andrewwestling** [comment]
I'm suspecting that the `collectstatic` command didn't run properly - try killing `heroku local` and starting it again

**Comment by chackerian** [comment]
ok. Getting same error.

**Comment by chackerian** [comment]
I was using sudo. Tried without it and it seems to be working. Now I just need login credentials.

**Comment by andrewwestling** [comment]
Ah, good to know 👍 

Let us know if you encounter other issues. Happy to help.

**Comment by andrewwestling** [comment]
A super user is automatically created in the setup script with the username **admin** and the password **architizer**

**Comment by chackerian** [comment]
oh ok, thanks

**Comment by chackerian** [comment]
Actually I still need more help. Login isn't working.

**Comment by andrewwestling** [comment]
If the login isn't working, you can try re-running the createsuperuser command in another window:

```
heroku local:run python manage.py createsuperuser
```

and follow the prompts to make a super user to use to access the app

The Django admin panel runs at http://localhost:5000/admin

Also, front end development for the project happens with a slightly different build pipeline - to run the front end for development, you have to run `gulp serve` from the `/mendel/angular` directory - this starts up a Browsersync server on http://localhost:3000/ so when you make changes to the front end files, the browser will update automatically.

**Comment by chackerian** [comment]
I got it to work by adding another user.

**Comment by picturedots** [comment]
@expandrew It turns out that he needed to run Postgres.app -- the instructions say that you have to install it, but don't explicitly say that is has to be running when you run the installation script.  But, you do.

**Comment by andrewwestling** [comment]
@picturedots Good to know - I've added a line to the README to clarify
